### ISSUE TITLE
Manage endpoints updated to support Tokens

### ISSUE THREAD

**Issue by jpvajda** [deepgram/deepgram-go-sdk#115]
Manage endpoints that will likely change:

* `request` - https://developers.deepgram.com/reference/get-request
* `requests`  - https://developers.deepgram.com/reference/get-all-requests
* `usage` - https://developers.deepgram.com/reference/summarize-usage
* `fields` - https://developers.deepgram.com/reference/get-fields"

**Comment by dvonthenen** [comment]
PR Merged. Will be available on the next release (hopefully today).
