### ISSUE TITLE
Fix Upload of Audio File to `/listen`

### ISSUE THREAD

**Issue by dvonthenen** [deepgram/deepgram-go-sdk#125]
## What is the current behavior?

When using the API `FromStream` and `FromFile`, the function call always returns this error:
`{"err_code":"Bad Request","err_msg":"Failed to process the payload. Ensure that it is less than 2 MB and contains valid UTF-8.","request_id":"082025b4-cdb0-4a1b-9d7a-31a1f8824ba3"}`

## Steps to reproduce

NA

## Expected behavior

This should just work

## Please tell us about your environment

Go SDK only

## Other information

NA

**Comment by rwrz** [comment]
@dvonthenen this is happening again on the v1.6.0

**Comment by dvonthenen** [comment]
hi @rwrz 

I will take a look this morning.

**Comment by dvonthenen** [comment]
This has been fixed and available in the this release:
https://github.com/deepgram/deepgram-go-sdk/releases/tag/v1.6.1
