### ISSUE TITLE
Handle `UtteranceEnd` message type 

### ISSUE THREAD

**Issue by boyswan** [deepgram/deepgram-go-sdk#146]
Using the `utterance_end_ms` parameter for the live api requires handling of `{ type: UtteranceEnd }`. Currently here's no way to handle this in the callback interface. 

Perhaps an optional `UnhandledResponse` method on the callback interface could be an useful escape-hatch for new message types, rather than treating it as an error?

**Comment by dvonthenen** [comment]
We just discussed this internally. Will expose this parameter shortly.

**Comment by dvonthenen** [comment]
in the meantime @boyswan , you can expose custom parameter to the Live Client using this example:
https://github.com/deepgram/deepgram-go-sdk/pull/144

This should get you around that problem.

**Comment by boyswan** [comment]
So this allows me to add the `utterance_end_ms` header, but what I'm referring to is an error from the router:

```
I1215 16:30:07.641232   96536 router.go:174] UnhandledMessage RAW:
{
  "type": "UtteranceEnd"
}
I1215 16:30:07.641236   96536 router.go:175] -----------------------------------------------


I1215 16:30:07.641253   96536 router.go:162] User callback is undefined
I1215 16:30:07.641257   96536 client.go:244] WebSocketClient::listen: router.Message failed. Err: invalid message type
```

**Comment by dvonthenen** [comment]
> So this allows me to add the `utterance_end_ms` header, but what I'm referring to is an error from the router:
> 
> ```
> I1215 16:30:07.641232   96536 router.go:174] UnhandledMessage RAW:
> {
>   "type": "UtteranceEnd"
> }
> I1215 16:30:07.641236   96536 router.go:175] -----------------------------------------------
> 
> 
> I1215 16:30:07.641253   96536 router.go:162] User callback is undefined
> I1215 16:30:07.641257   96536 client.go:244] WebSocketClient::listen: router.Message failed. Err: invalid message type
> ```

Not the header... you want to add as a query parameter. Just this one:
```
// example on how to send a custom parameter
params := make(map[string][]string, 0)
params["utterances"] = []string{"true"}
ctx = cfginterfaces.WithCustomParameters(ctx, params)
```

**Comment by dvonthenen** [comment]
Didn't mean to close with comment...

**Comment by boyswan** [comment]
Sorry typo! Meant parameter:

```
params := make(map[string][]string, 0)
params["utterance_end_ms"] = []string{"2000"}
ctx = cfginterfaces.WithCustomParameters(ctx, params)
```

If I understand correctly, the router needs to handle the UtteranceEnd type:
https://github.com/deepgram/deepgram-go-sdk/blob/1e72d2de26406a4ec69de948efab64ddd9c7c06c/pkg/api/live/v1/router.go#L49

**Comment by dvonthenen** [comment]
> Sorry typo! Meant parameter:
> 
> ```
> params := make(map[string][]string, 0)
> params["utterance_end_ms"] = []string{"2000"}
> ctx = cfginterfaces.WithCustomParameters(ctx, params)
> ```
> 
> If I understand correctly, the router needs to handle the UtteranceEnd type:
> 
> https://github.com/deepgram/deepgram-go-sdk/blob/1e72d2de26406a4ec69de948efab64ddd9c7c06c/pkg/api/live/v1/router.go#L49

Ahhhh that's right. There is a new message type that needs to be added. Will need to wait then until the modifications are complete. Forget about the new message type. Trying to juggle too many things right now.

**Comment by dvonthenen** [comment]
Released for GA
https://github.com/deepgram/deepgram-go-sdk/releases/tag/v1.0.2
