### ISSUE TITLE
Remove default `LogLevel` override 

### ISSUE THREAD

**Issue by boyswan** [deepgram/deepgram-go-sdk#150]
Currently there is no way to disable logs from `klog` as the default (0) is being overwritten with standard (1).

```go
if init.LogLevel == LogLevelDefault {
    init.LogLevel = LogLevelStandard
}

```

https://github.com/deepgram/deepgram-go-sdk/blob/main/pkg/common/init.go#L56

**Comment by dvonthenen** [comment]
Ooof... good catch

**Comment by dvonthenen** [comment]
I forgot this got update so default is just 0 which then sets to Standard.

If you set the value to anything other than default, it should work.

**Comment by dvonthenen** [comment]
Like this example:
https://github.com/deepgram/deepgram-go-sdk/blob/main/examples/prerecorded/file/main.go

**Comment by boyswan** [comment]
Maybe I'm misunderstanding, but I'm trying to disable logs all together. If I'm correct setting to 0 in klog will disable all logging, which is why I expected Default to do this, but the override to Standard makes no-logs impossible.

**Comment by dvonthenen** [comment]
The intent is to always generating logging to at least have certain informational and error messages be placed into the log by default. 

If you really, really want to disable logging, you are going to need to do this:
```
	common.Init(client.InitLib{
		LogLevel: common.LogLevel(-1), // LogLevelStandard / LogLevelFull / LogLevelTrace
	})
```

I tried this using `examples/prerecorded/file` and it should work for you. Not going to expose this in the API though.
