### ISSUE TITLE
Live `stream` logging error for `EOF`

### ISSUE THREAD

**Issue by boyswan** [deepgram/deepgram-go-sdk#156]
https://github.com/deepgram/deepgram-go-sdk/blob/main/pkg/client/live/client.go#L265

At the moment if the stream receives `EOF` it is still logged as an error. Should this be the case?

**Comment by dvonthenen** [comment]
The shutdown flow for your application should be stop the source of the audio then call `Stop()` on the websocket class. To your point though, I should handle that EOF error better in that function. Will take a look at that.

**Comment by dvonthenen** [comment]
PR merged. Available in v1.1
