### ISSUE TITLE
Add Numerals formatting feature

### ISSUE THREAD

**Issue by onur-yildirim-infinitusai** [deepgram/deepgram-go-sdk#183]
## Proposed changes
We need numeral formatting feature to be added to LiveTranscriptionOptions for feature parity.

## Possible Implementation
```
type LiveTranscriptionOptions struct {
	...
	Numerals        bool     `json:"numerals,omitempty" url:"numerals,omitempty"`
        ...
}
```

## Other information
It has been part of the codebase but reverted in this [commit](https://github.com/deepgram/deepgram-go-sdk/commit/e0ae2f2cfcf644fe4ba1cd958a45809a3ce40d97#diff-58005bea9307044cecc4cd4178550ec9ccea4c38b901d0985271251cf689a905). I didnt see any reasoning in the discussions or in the PR

**Comment by dvonthenen** [comment]
Hi @onur-yildirim-infinitusai 

Not sure how that got left off 🤔 I think maybe it got confused with "numbers" which is a deprecated feature.

In the meantime, you can add custom parameters using the following method:
https://github.com/deepgram/deepgram-go-sdk/blob/main/examples/streaming/microphone/main.go#L98-L101
