### ISSUE TITLE
Improved ErrorHandling for BadRequest

### ISSUE THREAD

**Issue by dmalmkvist** [deepgram/deepgram-go-sdk#218]
## Proposed changes
When `http.StatusBadRequest` return `StatusError` instead of `fmt.Errorf` 

## Context
This would simplify and make our error handling and reporting better. We expected that Deepgram request would return a `StatusError` with the HTTP status code, but is normally the case with the exception of `http.StatusBadRequest`

## Possible Implementation
https://github.com/deepgram/deepgram-go-sdk/blob/main/pkg/client/common/common.go#L94

## Other information
-

**Comment by dvonthenen** [comment]
It looks like the Deepgram Error Message was never implemented. I am working on a fix that should get you where, in most cases, it returns `StatusError`.

**Comment by dvonthenen** [comment]
PR merged. Will have a release this week.
