### ISSUE TITLE
Wrong type for `endpointing` param

### ISSUE THREAD

**Issue by deepankarm** [deepgram/deepgram-go-sdk#236]
Shouldn't `endpointing` be a boolean as per the [streaming API docs](https://developers.deepgram.com/reference/listen-live#query-params)? 

https://github.com/deepgram/deepgram-go-sdk/blob/a48acc88c2aaa5c29b2727cfff966d0ae1300237/pkg/client/interfaces/types-stream.go#L22

**Comment by dvonthenen** [comment]
Unless there are plans of deprecating the ability to specify the endpoint time, this should be a string and that particular documentation is wrong. Please see:
https://developers.deepgram.com/docs/endpointing
