### ISSUE TITLE
Websocket Client: data race on Stop()

### ISSUE THREAD

**Issue by robfig** [deepgram/deepgram-go-sdk#264]
## What is the current behavior?

I use the race detector in development to identify data races and crash my program. I found that it crashed after upgrading from the old Deepgram client to v1.5.0. Investigating that, it appears that it is difficult or impossible to use properly.

When running the streaming websocket client, it generally waits for new messages here:

https://github.com/deepgram/deepgram-go-sdk/blob/v1.5.0/pkg/client/listen/v1/websocket/client.go#L337

		msgType, byMsg, err := ws.ReadMessage()

If the user cancels the operation, I cancel the context provided to the client and call `client.Stop()`. 
That causes this race:

```
sfu-scribe | ==================
sfu-scribe | WARNING: DATA RACE
sfu-scribe | Write at 0x00c0005e0870 by goroutine 478:
sfu-scribe |   github.com/deepgram/deepgram-go-sdk/pkg/client/listen/v1/websocket.(*Client).Stop()
sfu-scribe |       /home/robfig/go/pkg/mod/github.com/deepgram/deepgram-go-sdk@v1.5.0/pkg/client/listen/v1/websocket/client.go:694 +0xa4
sfu-scribe |   main.relayDeepgramCaptions()
sfu-scribe |       /home/robfig/wonder/go/sfu/cmd/sfu-scribe/transcriptions.go:514 +0x144
sfu-scribe |   main.(*TranscriptionServer).StreamingRecognize.gowrap2()
sfu-scribe |       /home/robfig/wonder/go/sfu/cmd/sfu-scribe/transcriptions.go:161 +0x5d
sfu-scribe |
sfu-scribe | Previous read at 0x00c0005e0870 by goroutine 476:
sfu-scribe |   github.com/deepgram/deepgram-go-sdk/pkg/client/listen/v1/websocket.(*Client).internalConnectWithCancel()
sfu-scribe |       /home/robfig/go/pkg/mod/github.com/deepgram/deepgram-go-sdk@v1.5.0/pkg/client/listen/v1/websocket/client.go:161 +0x1c4
sfu-scribe |   github.com/deepgram/deepgram-go-sdk/pkg/client/listen/v1/websocket.(*Client).internalConnect()
sfu-scribe |       /home/robfig/go/pkg/mod/github.com/deepgram/deepgram-go-sdk@v1.5.0/pkg/client/listen/v1/websocket/client.go:148 +0x1e4
sfu-scribe |   github.com/deepgram/deepgram-go-sdk/pkg/client/listen/v1/websocket.(*Client).listen()
sfu-scribe |       /home/robfig/go/pkg/mod/github.com/deepgram/deepgram-go-sdk@v1.5.0/pkg/client/listen/v1/websocket/client.go:323 +0x160
sfu-scribe |   github.com/deepgram/deepgram-go-sdk/pkg/client/listen/v1/websocket.(*Client).internalConnectWithCancel.gowrap2()
sfu-scribe |       /home/robfig/go/pkg/mod/github.com/deepgram/deepgram-go-sdk@v1.5.0/pkg/client/listen/v1/websocket/client.go:266 +0x33
sfu-scribe |
```

The race detector complains about this line:

```
	c.retry = false
```

since it's read within `listen()`. 

I don't see any way for me to close the WS without this data race occurring. The line which reads from it does not respect context cancelation, and no other control flow besides Stop() closes the websocket.

## Steps to reproduce

My codebase is proprietary, but I believe that the race is clear from code inspection. 

## Expected behavior

The client should be able to be used concurrently without races.

**Comment by dvonthenen** [comment]
Ahhhh, yea. Technically, that should be within the connection mutex. Will update before the next release. I'm not super worried about it because the value is always true until you exit where it gets set false in that stop function.

**Comment by dvonthenen** [comment]
If you drop some code here, I can take a look at the problem you are having

**Comment by dvonthenen** [comment]
Will also put in a check to see if the context is valid within the stop function.

**Comment by dvonthenen** [comment]
Hi @robfig 

I think I have this fixed in this tag here. If you could give that a try to verify, that would be awesome:
https://github.com/deepgram/deepgram-go-sdk/tree/v1.5.1-dev.1

**Comment by robfig** [comment]
Thanks @dvonthenen , I'm not able to reproduce the data race with your change patched in.

**Comment by dvonthenen** [comment]
Awesome! Thanks for checking up on that! Will see about getting a release out there. In the meantime, you can continue to use that tag.

**Comment by dvonthenen** [comment]
The fix for this has been released here:
https://github.com/deepgram/deepgram-go-sdk/releases/tag/v1.6.0
